-- Spoofing/layering (market conduct). Spec: architecture.md "Detectors" section. Per participant
-- x instrument x venue x day, ratio of cancelled-unfilled order volume to submitted order
-- volume, z-scored against that participant's own trailing baseline AT THAT VENUE (venue-scoped
-- in DETECTOR_CALIBRATION -- order-book cancel-rate norms genuinely differ by venue, e.g.
-- Japannext's Night Market session). Same ZSCORE UDF as every statistical detector; no inline
-- threshold (market-agnostic rule #3).

USE ROLE ACCOUNTADMIN;
USE DATABASE VIGIL;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW SPOOFING_LAYERING_SIGNALS AS
WITH DAILY AS (
    SELECT
        PARTICIPANT_ID, INSTRUMENT_ID, VENUE_ID, JURISDICTION_ID,
        DATE(EVENT_TS) AS EVENT_DATE,
        SUM(CASE WHEN EVENT_TYPE = 'new' THEN QUANTITY ELSE 0 END) AS SUBMITTED_VOLUME,
        SUM(CASE WHEN EVENT_TYPE = 'cancel' AND FILLED_QUANTITY < QUANTITY THEN QUANTITY ELSE 0 END) AS CANCELLED_UNFILLED_VOLUME
    FROM ORDERS
    GROUP BY PARTICIPANT_ID, INSTRUMENT_ID, VENUE_ID, JURISDICTION_ID, DATE(EVENT_TS)
),
RATIO AS (
    SELECT *, DIV0(CANCELLED_UNFILLED_VOLUME, SUBMITTED_VOLUME) AS CANCEL_RATIO
    FROM DAILY
),
BASELINE AS (
    SELECT
        *,
        AVG(CANCEL_RATIO) OVER (
            PARTITION BY PARTICIPANT_ID, INSTRUMENT_ID, VENUE_ID
            ORDER BY EVENT_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
        ) AS BASELINE_MEAN,
        STDDEV(CANCEL_RATIO) OVER (
            PARTITION BY PARTICIPANT_ID, INSTRUMENT_ID, VENUE_ID
            ORDER BY EVENT_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
        ) AS BASELINE_STDDEV,
        COUNT(*) OVER (
            PARTITION BY PARTICIPANT_ID, INSTRUMENT_ID, VENUE_ID
            ORDER BY EVENT_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
        ) AS BASELINE_PERIODS
    FROM RATIO
)
SELECT
    b.*,
    c.Z_THRESHOLD,
    c.MIN_BASELINE_PERIODS,
    c.IS_PROVISIONAL,
    ZSCORE(b.CANCEL_RATIO, b.BASELINE_MEAN, b.BASELINE_STDDEV) AS CANCEL_RATIO_ZSCORE,
    (b.BASELINE_PERIODS >= c.MIN_BASELINE_PERIODS
     AND ZSCORE(b.CANCEL_RATIO, b.BASELINE_MEAN, b.BASELINE_STDDEV) IS NOT NULL
     AND ABS(ZSCORE(b.CANCEL_RATIO, b.BASELINE_MEAN, b.BASELINE_STDDEV)) >= c.Z_THRESHOLD
    ) AS IS_FLAGGED
FROM BASELINE b
JOIN DETECTOR_CALIBRATION_CURRENT c
    ON c.JURISDICTION_ID = b.JURISDICTION_ID
   AND c.VENUE_ID = b.VENUE_ID
   AND c.DETECTOR_NAME = 'spoofing_layering';

GRANT SELECT ON VIEW SPOOFING_LAYERING_SIGNALS TO ROLE ANALYST_READ;
