-- SURVEILLANCE_RUN_LOG: a read view over AUDIT_LOG WHERE STAGE = 'surveillance_run', normalizing
-- each detector's own JSON shape (SP_LOG_SURVEILLANCE_RUN's OUTPUT column) into one FLAGGED_COUNT
-- column, so a downstream consumer (Semantic View, agent, dashboard) needs one column instead of
-- four detector-specific JSON extractions. Captured here from CoCo's live Snowflake object
-- (created directly via sql_execute, never originally saved to a file) so it's reproducible from
-- sql/ alone -- see NOTES.md/TRACKER.md for the full CoCo-build writeup.
--
-- No milestoning columns of its own: this is a pure derived view over AUDIT_LOG, which is already
-- append-only and immutable -- there is nothing here to version independently of the base table.

USE ROLE ACCOUNTADMIN;
USE DATABASE VIGIL;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW SURVEILLANCE_RUN_LOG(
    RUN_ID,
    DETECTOR_NAME,
    QUERY_SNAPSHOT_ID,
    CREATED_AT,
    APP_USER,
    FLAGGED_COUNT
) AS
-- FLAGGED_COUNT is a single normalized integer whose meaning depends on DETECTOR_NAME:
--   wash_trading:          OUTPUT:non_exempt_candidates  (exempt candidates excluded)
--   spoofing_layering:     OUTPUT:flagged_signals        (z-score above threshold)
--   position_limit:        OUTPUT:breaches               (positions >= regulatory limit)
--   reporting_timeliness:  SUM of OUTPUT:overdue_unsubmitted + late_submissions
--                              + incomplete_reports + mismatched_reports
--   best_execution:        OUTPUT:execution_slippage_uncheckable -- NOTE, different semantics
--                              from the other four: this is a coverage gap (trades with no
--                              reference price to check against), not a compliance breach --
--                              TRADE_REFERENCE_PRICES isn't populated by the synthetic generator,
--                              so this currently equals total_trades every run, honestly.
-- This mapping lives here (the one place the count's meaning is detector-dependent)
-- so every downstream consumer -- Semantic View, agent, dashboard -- gets one column
-- instead of five detector-specific JSON extractions.
SELECT
    RUN_ID,
    PROMPT_OR_QUESTION                              AS DETECTOR_NAME,
    QUERY_SNAPSHOT_ID,
    CREATED_AT,
    APP_USER,
    CASE PROMPT_OR_QUESTION
        WHEN 'wash_trading'
            THEN PARSE_JSON(OUTPUT):non_exempt_candidates::NUMBER
        WHEN 'spoofing_layering'
            THEN PARSE_JSON(OUTPUT):flagged_signals::NUMBER
        WHEN 'position_limit'
            THEN PARSE_JSON(OUTPUT):breaches::NUMBER
        WHEN 'reporting_timeliness'
            THEN COALESCE(PARSE_JSON(OUTPUT):overdue_unsubmitted::NUMBER, 0)
               + COALESCE(PARSE_JSON(OUTPUT):late_submissions::NUMBER, 0)
               + COALESCE(PARSE_JSON(OUTPUT):incomplete_reports::NUMBER, 0)
               + COALESCE(PARSE_JSON(OUTPUT):mismatched_reports::NUMBER, 0)
        WHEN 'best_execution'
            THEN PARSE_JSON(OUTPUT):execution_slippage_uncheckable::NUMBER
    END                                             AS FLAGGED_COUNT
FROM VIGIL.CORE.AUDIT_LOG
WHERE STAGE = 'surveillance_run';

GRANT SELECT ON VIEW SURVEILLANCE_RUN_LOG TO ROLE ANALYST_READ;

-- DOCUMENTED_FINDINGS_LOG: a read view over AUDIT_LOG WHERE STAGE = 'documented_finding' --
-- the actual per-report assurance verdicts written by scripts/generate_documented_findings.py
-- via SP_LOG_DOCUMENTED_FINDING (sql/procedures/sp_log_documented_finding.sql). This is the
-- "documented finding" step of signal -> evidence -> documented finding: SURVEILLANCE_RUN_LOG
-- above is the evidence (a count), this is the finding itself (a real per-report verdict, with
-- exact reasons, generated by the already-tested skills/assure_report.py logic, not a SQL
-- approximation -- SOURCE_MAPPING is free text, Fix #9's documented unenforceable-in-SQL
-- limitation, which is exactly why this stays a Python script rather than another SQL view).
CREATE OR REPLACE VIEW DOCUMENTED_FINDINGS_LOG(
    RUN_ID,
    REPORT_ID,
    CREATED_AT,
    APP_USER,
    READY_TO_SUBMIT,
    FIELDS_COMPLETE,
    UNRESOLVED_REQUIRED_FIELDS,
    GAP_FIELDS,
    REASONS
) AS
SELECT
    RUN_ID,
    PROMPT_OR_QUESTION                              AS REPORT_ID,
    CREATED_AT,
    APP_USER,
    PARSE_JSON(OUTPUT):ready_to_submit::BOOLEAN     AS READY_TO_SUBMIT,
    PARSE_JSON(OUTPUT):fields_complete::BOOLEAN     AS FIELDS_COMPLETE,
    PARSE_JSON(OUTPUT):unresolved_required_fields   AS UNRESOLVED_REQUIRED_FIELDS,
    PARSE_JSON(OUTPUT):gap_fields                   AS GAP_FIELDS,
    PARSE_JSON(OUTPUT):reasons                      AS REASONS
FROM VIGIL.CORE.AUDIT_LOG
WHERE STAGE = 'documented_finding';

GRANT SELECT ON VIEW DOCUMENTED_FINDINGS_LOG TO ROLE ANALYST_READ;
