-- Five functional roles per architecture.md's RBAC section + docs/canonical_schema_contract.md's
-- "RBAC additions" section. This file creates the roles and their baseline USAGE grants
-- (database/schema/warehouse) -- the actual table/view privilege grants are in the per-role
-- files that follow (02-05) and sql/procedures/.
--
-- Blanket rule (milestoning discipline point 3): no grant script in this directory ever issues
-- UPDATE or DELETE on any VIGIL.CORE object, full stop.
--
-- Roles are granted to SYSADMIN (standard Snowflake practice so the role hierarchy stays
-- manageable) and to the current user, so each can actually be assumed and tested (Phase 7).

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ANALYST_READ;
CREATE ROLE IF NOT EXISTS GOVERNANCE_WRITE;
CREATE ROLE IF NOT EXISTS AUDIT_INSERT;
CREATE ROLE IF NOT EXISTS OFFICER_SIGNOFF;
CREATE ROLE IF NOT EXISTS MARKET_DATA_INGEST;

GRANT ROLE ANALYST_READ TO ROLE SYSADMIN;
GRANT ROLE GOVERNANCE_WRITE TO ROLE SYSADMIN;
GRANT ROLE AUDIT_INSERT TO ROLE SYSADMIN;
GRANT ROLE OFFICER_SIGNOFF TO ROLE SYSADMIN;
GRANT ROLE MARKET_DATA_INGEST TO ROLE SYSADMIN;

GRANT ROLE ANALYST_READ TO USER ASHWINISHARMA0807;
GRANT ROLE GOVERNANCE_WRITE TO USER ASHWINISHARMA0807;
GRANT ROLE AUDIT_INSERT TO USER ASHWINISHARMA0807;
GRANT ROLE OFFICER_SIGNOFF TO USER ASHWINISHARMA0807;
GRANT ROLE MARKET_DATA_INGEST TO USER ASHWINISHARMA0807;

GRANT USAGE ON DATABASE VIGIL TO ROLE ANALYST_READ;
GRANT USAGE ON DATABASE VIGIL TO ROLE GOVERNANCE_WRITE;
GRANT USAGE ON DATABASE VIGIL TO ROLE AUDIT_INSERT;
GRANT USAGE ON DATABASE VIGIL TO ROLE OFFICER_SIGNOFF;
GRANT USAGE ON DATABASE VIGIL TO ROLE MARKET_DATA_INGEST;

GRANT USAGE ON SCHEMA VIGIL.CORE TO ROLE ANALYST_READ;
GRANT USAGE ON SCHEMA VIGIL.CORE TO ROLE GOVERNANCE_WRITE;
GRANT USAGE ON SCHEMA VIGIL.CORE TO ROLE AUDIT_INSERT;
GRANT USAGE ON SCHEMA VIGIL.CORE TO ROLE OFFICER_SIGNOFF;
GRANT USAGE ON SCHEMA VIGIL.CORE TO ROLE MARKET_DATA_INGEST;

-- No role above is granted anything on VIGIL.EVAL -- that schema stays isolated by omission
-- (it holds no tables yet; INJECTED_CASES/EVAL_RESULTS are future work, not in this build order).

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST_READ;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE GOVERNANCE_WRITE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AUDIT_INSERT;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE OFFICER_SIGNOFF;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MARKET_DATA_INGEST;
