-- ANALYST_READ: SELECT only, everywhere listed below. No write access anywhere (architecture.md
-- RBAC section). Deliberately excludes: base OBLIGATION_MAP/OBLIGATION_MAP_CURRENT (Fix #6 --
-- GOVERNANCE_WRITE only, so an unapproved obligation is structurally invisible here), AUDIT_LOG
-- (no role gets SELECT on it), DETECTOR_CALIBRATION/_CURRENT (detector views read it via
-- owner's-rights view execution, not via a direct grant to this role).
--
-- WASH_DETECTION_COVERAGE is NOT granted here -- that view doesn't exist yet (Phase 3). Its
-- SELECT grant to this role is added in sql/detectors/ once the view is created.

USE ROLE ACCOUNTADMIN;
USE DATABASE VIGIL;
USE SCHEMA CORE;

-- Rule corpus + governance-gate view
GRANT SELECT ON TABLE RULE_CORPUS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW RULE_CORPUS_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW APPROVED_OBLIGATIONS TO ROLE ANALYST_READ;

-- Reference data
GRANT SELECT ON TABLE JURISDICTIONS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW JURISDICTIONS_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE VENUES TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW VENUES_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE BENEFICIAL_OWNERS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW BENEFICIAL_OWNERS_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE INSTRUMENTS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW INSTRUMENTS_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE MARKET_PARTICIPANTS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW MARKET_PARTICIPANTS_CURRENT TO ROLE ANALYST_READ;

-- Orders / trades / positions
GRANT SELECT ON TABLE ORDERS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW ORDERS_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE TRADES TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE TRADE_CORRECTIONS TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE TRADE_REFERENCE_PRICES TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW TRADE_REFERENCE_PRICES_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE POSITIONS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW POSITIONS_CURRENT TO ROLE ANALYST_READ;

-- Reporting
GRANT SELECT ON TABLE TRANSACTION_REPORTS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW TRANSACTION_REPORTS_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE REPORT_TEMPLATES TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW REPORT_TEMPLATES_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON TABLE REPORT_TEMPLATE_RULE_CHUNKS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW REPORT_TEMPLATE_RULE_CHUNKS_CURRENT TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW REPORT_TEMPLATE_COVERAGE TO ROLE ANALYST_READ;

-- Obligation citation trail (junction table only -- not the base OBLIGATION_MAP)
GRANT SELECT ON TABLE OBLIGATION_RULE_CHUNKS TO ROLE ANALYST_READ;
GRANT SELECT ON VIEW OBLIGATION_RULE_CHUNKS_CURRENT TO ROLE ANALYST_READ;
