-- GOVERNANCE_WRITE: INSERT-only on OBLIGATION_MAP/OBLIGATION_RULE_CHUNKS (Fix #12 -- the
-- proposed->approved flip is a new row, never an UPDATE), INSERT on RULE_CORPUS, plus SELECT on
-- the base OBLIGATION_MAP table (to see proposed rows ANALYST_READ cannot, via APPROVED_
-- OBLIGATIONS only). Also INSERT-only on REPORT_TEMPLATES/REPORT_TEMPLATE_RULE_CHUNKS (Fix #21
-- -- a report template is regulatory content, same category as RULE_CORPUS/OBLIGATION_MAP, not
-- raw market data routed through MARKET_DATA_INGEST).
--
-- Never UPDATE/DELETE on anything (milestoning discipline rule 3) -- this file issues INSERT and
-- one SELECT grant only.

USE ROLE ACCOUNTADMIN;
USE DATABASE VIGIL;
USE SCHEMA CORE;

GRANT INSERT ON TABLE OBLIGATION_MAP TO ROLE GOVERNANCE_WRITE;
GRANT SELECT ON TABLE OBLIGATION_MAP TO ROLE GOVERNANCE_WRITE;
GRANT INSERT ON TABLE OBLIGATION_RULE_CHUNKS TO ROLE GOVERNANCE_WRITE;
GRANT INSERT ON TABLE RULE_CORPUS TO ROLE GOVERNANCE_WRITE;
GRANT INSERT ON TABLE REPORT_TEMPLATES TO ROLE GOVERNANCE_WRITE;
GRANT INSERT ON TABLE REPORT_TEMPLATE_RULE_CHUNKS TO ROLE GOVERNANCE_WRITE;
