-- MARKET_DATA_INGEST (new, Fix #7): INSERT-only on every market-data table -- every lifecycle
-- event on these tables (a VENUES status change, an ORDERS event, a TRANSACTION_REPORTS
-- submission, a POSITIONS restatement) is an INSERT by design (Fixes #4, #10, #14, #16), so this
-- role never needs UPDATE/DELETE and is never granted it. Also gains SELECT on
-- REPORT_TEMPLATES_CURRENT (Fix #21) -- its only SELECT grant, needed to know which fields are
-- required before generating a TRANSACTION_REPORTS payload. No base-table read access anywhere
-- else.

USE ROLE ACCOUNTADMIN;
USE DATABASE VIGIL;
USE SCHEMA CORE;

GRANT INSERT ON TABLE JURISDICTIONS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE VENUES TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE INSTRUMENTS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE MARKET_PARTICIPANTS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE BENEFICIAL_OWNERS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE ORDERS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE TRADES TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE TRADE_CORRECTIONS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE TRANSACTION_REPORTS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE POSITIONS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE TRADE_REFERENCE_PRICES TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE CORPORATE_ACTIONS TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE DERIVATIVE_PRODUCT_ATTRIBUTES TO ROLE MARKET_DATA_INGEST;
GRANT INSERT ON TABLE DERIVATIVE_TRADE_DETAILS TO ROLE MARKET_DATA_INGEST;

GRANT SELECT ON VIEW REPORT_TEMPLATES_CURRENT TO ROLE MARKET_DATA_INGEST;
